version: "3"
services:
  app:
    build:
      context: ./challenge
      dockerfile: ./Dockerfile
    container_name: hash_overdrive
    user: ctf
    working_dir: /home/ctf
    entrypoint: /bin/sh -c "./ynetd -p 6969 /home/ctf/launch.sh"
    ports:
      - "5778:6969"
    privileged: true
    read_only: true